[package]
name = "mirafmt"
version = "0.1.0"
edition = "2024"

[dependencies]
mira = { path = "../mira" }
mira-macros = { path = "../mira-macros" }
mira-errors = { path = "../mira-errors" }
mira-spans = { path = "../mira-spans" }
