pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub mod context;
pub mod linking;
pub mod optimizations;
pub mod target;
pub mod threadpool;
pub mod typechecking;
pub use mira_errors::{AsciiPrinter, Output, UnicodePrinter};
pub use mira_spans::Arena;
pub use mira_spans::interner::symbols;
mod lang_items;
