pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub mod annotations;
pub mod error;
pub mod lang_items;
pub mod linking;
pub mod module;
pub mod parser;
pub mod std_annotations;
pub mod target;
pub mod tokenstream;
pub mod typechecking;
pub use parser::module_resolution;
pub mod context;
pub mod optimizations;
pub mod store;
pub mod threadpool;
pub use mira_errors::{AsciiPrinter, Output, UnicodePrinter};
pub use mira_spans::Arena;
pub use mira_spans::interner::symbols;
